MvcProjeKampi/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        Context c = new Context(); // 1.
        int writerIdInfo;
        public ActionResult WriterProfile()
        {
            return View();
        }

        public ActionResult MyHeading(string p)
        {
            p = (string)Session["WriterMail"]; // 2. 
            writerIdInfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault(); // 3. Birinci, ikinci ve üçüncü satır solide uyuyor mu? Düzeltilebilir mi?
            var values = hm.GetListByWriter(writerIdInfo);
            return View(values);
        }

        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }
                                                 ).ToList();
            ViewBag.vlc = valueCategory;
            return View();
        }

        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {
            string writerMailInfo = (string)Session["WriterMail"];
            writerIdInfo = c.Writers.Where(x => x.WriterMail == writerMailInfo).Select(y => y.WriterID).FirstOrDefault(); // 3. Birinci, ikinci ve üçüncü satır solide uyuyor mu? Düzeltilebilir mi?
            ViewBag.d = writerIdInfo;
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = writerIdInfo;
            p.HeadingStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("MyHeading");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }
                                                  ).ToList();
            ViewBag.vlc = valueCategory;
            var headingValue = hm.GetByID(id);
            return View(headingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("MyHeading");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetByID(id);
            headingValue.HeadingStatus = false;
            hm.HeadingDelete(headingValue);
            return RedirectToAction("MyHeading");
        }
    }
}

MvcProjeKampi/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{
<div class="form-group">

    @Html.HiddenFor(x => x.HeadingID)
    @Html.HiddenFor(x => x.HeadingDate)
    @Html.HiddenFor(x => x.WriterID)
    <br />
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

MvcProjeKampi/Views/WriterPanel/MyHeading.cshtml
@using EntityLayer.Concrete
@model  List<Heading>

@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@{ string color = "";}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyat")
                            {
                                color = "badge badge-warning";
                            }

                            if (item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Film")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryName == "Dizi")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-info   ";
                            }
                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            @item.Writer.WriterName @item.Writer.WriterSurname
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerikler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    @if (item.HeadingStatus == true)
                                    {
                                        <a class="btn btn-danger btn-sm" href="/WriterPanel/DeleteHeading/@item.HeadingID">
                                            <i class="fas fa-trash">
                                            </i>
                                            <span>Sil</span>
                                        </a>
                                    }

                                    else
                                    {
                                        <a class="btn btn-success btn-sm" href="/Heading/ActivateHeading/@item.HeadingID">
                                            <i class="fas fa-trash">
                                            </i>
                                            <span>Ekle</span>
                                        </a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
</body>
</html>
<a href="/WriterPanel/NewHeading/" class="btn btn-primary">Yeni Başlık Oluştur</a>

MvcProjeKampi/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Yeni Başlık Ekleme</h1>
<h2>@ViewBag.d</h2>
<br />
@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @*@Html.Label("Yazar Başlığı")
            @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.WriterID, null, new { @class = "text-danger" })*@
        <br />
        <button class="btn btn-info">Başlığı Oluştur</button>
    </div>
}

MvcProjeKampi/Views/WriterPanel/WriterProfile.cshtml
@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>WriterProfile</h2>